name: Book
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo install mdbook
      - run: mdbook build docs
  deploy:
    name: Deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update nightly && rustup default nightly
      - run: cargo install mdbook
      - run: mdbook build docs
      - run: RUSTDOCFLAGS="-D warnings --cfg doc_cfg" cargo +nightly doc --workspace --all-features --no-deps --document-private-items
      - run: mkdir -p ./docs/book/rustdoc
      - run: mv ./target/doc ./docs/book/rustdoc/latest
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
